variable "myregion" {}
variable "accountId" {}
variable "apigw_name" {}
variable "uri_get_movies" {}
variable "uri_by_year" {}
variable "uri_generate_summary" {}
variable "function_name_get_movies" {}
variable "function_name_by_year" {}
variable "function_name_generate_summary" {}