export const movies = [
  {
    title: "Inception",
    releaseYear: "2010",
    genre: "Science, Fiction",
    coverUrl: "",
  },
  {
    title: "The Godfather",
    releaseYear: "1972",
    genre: "Crime, Drama",
    coverUrl: "",
  },
  {
    title: "The Dark Knight",
    releaseYear: "2008",
    genre: "Action, Crime, Drama",
    coverUrl: "",
  },
  {
    title: "Forrest Gump",
    releaseYear: "1994",
    genre: "Drama, Romance",
    coverUrl: "",
  },
  {
    title: "The Matrix",
    releaseYear: "1999",
    genre: "Science, Fiction, Action",
    coverUrl: "",
  },
  {
    title: "Pulp Fiction",
    releaseYear: "1994",
    genre: "Crime, Drama",
    coverUrl: "",
  },
  {
    title: "Interstellar",
    releaseYear: "2014",
    genre: "Science, Fiction, Adventure",
    coverUrl: "",
  },
  {
    title: "Gladiator",
    releaseYear: "2000",
    genre: "Action, Adventure, Drama",
    coverUrl: "",
  },
  {
    title: "The Shawshank Redemption",
    releaseYear: "1994",
    genre: "Drama",
    coverUrl: "",
  },
  {
    title: "Avengers: Endgame",
    releaseYear: "2019",
    genre: "Action, Adventure, Science, Fiction",
    coverUrl: "",
  },
  {
    title: "Fight Club",
    releaseYear: "1999",
    genre: "Drama",
    coverUrl: "",
  },
  {
    title: "Goodfellas",
    releaseYear: "1990",
    genre: "Crime, Drama",
    coverUrl: "",
  },
  {
    title: "The Silence of the Lambs",
    releaseYear: "1991",
    genre: "Thriller",
    coverUrl: "",
  },
  {
    title: "Schindler's List",
    releaseYear: "1993",
    genre: "Historical, Drama",
    coverUrl: "",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    releaseYear: "2001",
    genre: "Fantasy",
    coverUrl: "",
  },
  {
    title: "Star Wars: Episode IV - A New Hope",
    releaseYear: "1977",
    genre: "Science, Fiction",
    coverUrl: "",
  },
  {
    title: "Jurassic Park",
    releaseYear: "1993",
    genre: "Science, Fiction",
    coverUrl: "",
  },
  {
    title: "Titanic",
    releaseYear: "1997",
    genre: "Romance, Drama",
    coverUrl: "",
  },
  {
    title: "The Green Mile",
    releaseYear: "1999",
    genre: "Drama",
    coverUrl: "",
  },
  {
    title: "The Departed",
    releaseYear: "2006",
    genre: "Crime, Drama",
    coverUrl: "",
  },
  {
    title: "Saving Private Ryan",
    releaseYear: "1998",
    genre: "War, Drama",
    coverUrl: "",
  },
  {
    title: "The Usual Suspects",
    releaseYear: "1995",
    genre: "Crime, Thriller",
    coverUrl: "",
  },
  {
    title: "Memento",
    releaseYear: "2000",
    genre: "Thriller",
    coverUrl: "",
  },
  {
    title: "The Lion King",
    releaseYear: "1994",
    genre: "Animation",
    coverUrl: "",
  },
  {
    title: "Back to the Future",
    releaseYear: "1985",
    genre: "Science, Fiction",
    coverUrl: "",
  },
  {
    title: "The Terminator",
    releaseYear: "1984",
    genre: "Science, Fiction",
    coverUrl: "",
  },
  {
    title: "Alien",
    releaseYear: "1979",
    genre: "Science, Fiction, Horror",
    coverUrl: "",
  },
  {
    title: "The Sixth Sense",
    releaseYear: "1999",
    genre: "Supernatural, Thriller",
    coverUrl: "",
  },
  {
    title: "Die Hard",
    releaseYear: "1988",
    genre: "Action",
    coverUrl: "",
  },
  {
    title: "The Shining",
    releaseYear: "1980",
    genre: "Horror",
    coverUrl: "",
  },
  {
    title: "A Beautiful Mind",
    releaseYear: "2001",
    genre: "Biographical, Drama",
    coverUrl: "",
  },
  {
    title: "The Social Network",
    releaseYear: "2010",
    genre: "Biographical, Drama",
    coverUrl: "",
  },
  {
    title: "Good Will Hunting",
    releaseYear: "1997",
    genre: "Drama",
  },
  {
    title: "12 Angry Men",
    releaseYear: "1957",
    genre: "Drama",
  },
]
